# -*- coding: utf-8 -*-
"""生成测试用 .cube LUT（供安卓 RawLab 通用 LUT 模式真机验证）。

三张输出（33³，R-fast，标准 .cube 结构，刻意不带 #Gamma/#Gamut 合约注释——
即 DISPLAY 模式的标准输入；输入空间为 sRGB 显示编码值）：
  1. identity.cube       恒等表：套用后必须与中性画面逐像素一致（GPU/CPU 一致性诊断）
  2. portra-warm.cube    低反差暖调人像（胶片负片味：暗部抬升、高光收拢、轻降饱和、暖偏移）
  3. teal-orange.cube    青橙调（阴影推青、高光推橙，电影海报风）

所有变换为点态、平滑、单调（R/G/B 各通道曲线 + 通道耦合），是合法 3D LUT 对象。
运行：python make_test_luts.py [输出目录]
"""
import numpy as np
import sys, os

N = 33

def srgb_to_linear(x):
    return np.where(x <= 0.04045, x / 12.92, ((x + 0.055) / 1.055) ** 2.4)

def linear_to_srgb(x):
    x = np.clip(x, 0.0, 1.0)
    return np.where(x <= 0.0031308, x * 12.92, 1.055 * np.clip(x, 0, 1) ** (1 / 2.4) - 0.055)

def lift_gamma_gain(x, lift, gamma, gain):
    """经典 LGT：0 点抬到 lift，1 点收到 gain，中间 gamma 控制中调。"""
    x = np.clip(x, 0.0, 1.0)
    y = lift + (gain - lift) * np.power(x, 1.0 / gamma)
    return np.clip(y, 0.0, 1.0)

def smooth_saturation(rgb, amount):
    """绕亮度轴的饱和度缩放（平滑、无色相旋转）。amount<1 降饱和，>1 增饱和。"""
    lum = rgb @ np.array([0.2126, 0.7152, 0.0722])
    return lum.reshape(-1, 1) + (rgb - lum.reshape(-1, 1)) * amount

# 行对角占优的正常数矩阵：每行 sum>0 且 |非对角| 远小于对角，
# 数学上保证"沿任一输入轴遍历时该通道输出单调不降"。
MATRIX_PORTRA = np.array([
    [1.05, 0.00, -0.04],
    [0.00, 1.00,  0.00],
    [-0.05, 0.00, 1.04],
])
MATRIX_TEAL = np.array([
    [1.07, -0.03, -0.04],
    [-0.02, 1.02, -0.02],
    [-0.05, -0.01, 1.07],
])

def portra_warm(rgb):
    """低反差暖调：暗部抬升（R 最高=偏暖棕，负片特征）、高光收拢、降饱和 0.92。"""
    lin = srgb_to_linear(rgb)
    disp = linear_to_srgb(np.clip(lin @ MATRIX_PORTRA.T, 0.0, 1.0))
    out = np.stack([
        lift_gamma_gain(disp[:, 0], 0.045, 0.94, 0.97),
        lift_gamma_gain(disp[:, 1], 0.034, 0.94, 0.97),
        lift_gamma_gain(disp[:, 2], 0.028, 0.94, 0.97),
    ], axis=1)
    out = smooth_saturation(out, 0.92)
    return np.clip(out, 0.0, 1.0)

MATRIX_PORTRA_VIVID = np.array([
    [1.10, 0.00, -0.05],
    [0.00, 1.00,  0.00],
    [-0.06, 0.00, 1.08],
])
MATRIX_TEAL_VIVID = np.array([
    [1.18, -0.08, -0.10],
    [-0.05, 1.05, -0.05],
    [-0.12, -0.03, 1.16],
])

def portra_warm_vivid(rgb):
    """夸张版：强温移 + 暗部大幅抬升 + 强降饱和，一眼可辨的褪色暖调。"""
    lin = srgb_to_linear(rgb)
    disp = linear_to_srgb(np.clip(lin @ MATRIX_PORTRA_VIVID.T, 0.0, 1.0))
    out = np.stack([
        lift_gamma_gain(disp[:, 0], 0.10, 0.88, 0.94),
        lift_gamma_gain(disp[:, 1], 0.085, 0.88, 0.94),
        lift_gamma_gain(disp[:, 2], 0.045, 0.88, 0.94),
    ], axis=1)
    out = smooth_saturation(out, 0.78)
    return np.clip(out, 0.0, 1.0)

def teal_orange_vivid(rgb):
    """夸张版：强 split-tone + 增饱和 1.30，阴影青蓝、暖物橙红一眼可辨。"""
    lin = srgb_to_linear(rgb)
    disp = linear_to_srgb(np.clip(lin @ MATRIX_TEAL_VIVID.T, 0.0, 1.0))
    out = np.stack([
        lift_gamma_gain(disp[:, 0], 0.0, 0.82, 1.0),
        lift_gamma_gain(disp[:, 1], 0.0, 0.98, 1.0),
        lift_gamma_gain(disp[:, 2], 0.0, 1.24, 1.0),
    ], axis=1)
    out = smooth_saturation(out, 1.30)
    return np.clip(out, 0.0, 1.0)

def teal_orange(rgb):
    """青橙底子：R/B 通道反差扩大（对角占优矩阵实现 split-tone）+ 轻 S 曲线 + 增饱和 1.06。"""
    lin = srgb_to_linear(rgb)
    disp = linear_to_srgb(np.clip(lin @ MATRIX_TEAL.T, 0.0, 1.0))
    # 逐通道轻 S 曲线（单调）：提亮中调对比
    out = np.stack([
        lift_gamma_gain(disp[:, 0], 0.0, 0.90, 1.0),
        lift_gamma_gain(disp[:, 1], 0.0, 1.00, 1.0),
        lift_gamma_gain(disp[:, 2], 0.0, 1.12, 1.0),
    ], axis=1)
    out = smooth_saturation(out, 1.06)
    return np.clip(out, 0.0, 1.0)

def write_cube(path, title, table):
    """table: (N³, 3) float [0,1]，R-fast 排布。"""
    with open(path, "w", newline="\n") as f:
        f.write(f'TITLE "{title}"\n')
        f.write("# Generated by RawLab make_test_luts.py for device verification.\n")
        f.write(f"LUT_3D_SIZE {N}\n\n")
        for row in table:
            f.write(f"{row[0]:.6f} {row[1]:.6f} {row[2]:.6f}\n")

def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(out_dir, exist_ok=True)
    # R-fast：r 变化最快（与 .cube 规范和仓库解析器一致）
    b, g, r = np.meshgrid(*([np.linspace(0, 1, N)] * 3), indexing="ij")
    grid = np.stack([r.ravel(), g.ravel(), b.ravel()], axis=1)

    write_cube(os.path.join(out_dir, "identity.cube"), "Identity (RawLab test)",
               grid.copy())
    write_cube(os.path.join(out_dir, "portra-warm.cube"), "Portra-like Warm Portrait (RawLab test)",
               portra_warm(grid))
    write_cube(os.path.join(out_dir, "teal-orange.cube"), "Teal and Orange (RawLab test)",
               teal_orange(grid))
    write_cube(os.path.join(out_dir, "portra-warm-vivid.cube"), "Portra-like Warm VIVID (RawLab test)",
               portra_warm_vivid(grid))
    write_cube(os.path.join(out_dir, "teal-orange-vivid.cube"), "Teal and Orange VIVID (RawLab test)",
               teal_orange_vivid(grid))

    # 自检：identity 恒等；主对角单调（每通道沿自己的轴不降——
    # 跨通道微降是饱和度>1 与 split-tone 矩阵的数学必然，不属于 banding 翻车点）
    # + 中性对角线单调。注意 grid 是 R-fast：reshape 后 r=axis2、g=axis1、b=axis0。
    ident = grid
    for name, fn in [("portra-warm", portra_warm), ("teal-orange", teal_orange),
                     ("portra-warm-vivid", portra_warm_vivid), ("teal-orange-vivid", teal_orange_vivid)]:
        t = fn(grid).reshape(N, N, N, 3)
        # 容差 1e-3（0.25/255）：饱和度绕亮度的混合会把 clip 平顶端的其它通道
        # 拉回 ≤0.1%，属算法固有交互，任何屏幕/导出位深下不可见。
        tol = -1e-3
        main_mono = (np.all(np.diff(t[:, :, :, 0], axis=2) >= tol) and
                     np.all(np.diff(t[:, :, :, 1], axis=1) >= tol) and
                     np.all(np.diff(t[:, :, :, 2], axis=0) >= tol))
        diag = fn(np.stack([np.linspace(0, 1, 1024)] * 3, axis=1))
        diag_mono = np.all(np.diff(diag, axis=0) >= -1e-6)
        gray = fn(np.array([[0.0, 0.0, 0.0], [0.18, 0.18, 0.18], [0.5, 0.5, 0.5], [1.0, 1.0, 1.0]]))
        print(f"{name}: main-mono={main_mono} neutral-ramp-mono={diag_mono} "
              f"black={gray[0].round(3)} gray18={gray[1].round(3)} mid={gray[2].round(3)} white={gray[3].round(3)}")
    print(f"identity: exact={np.array_equal(ident, grid)}")
    print(f"输出目录: {os.path.abspath(out_dir)}")

if __name__ == "__main__":
    main()
